CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260818174809_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "NormalizedName" character varying(100) NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Price" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "ImageUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Categories_NormalizedName" ON "Categories" ("NormalizedName");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908172454_AddAdminCategories', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "CreatedById" integer;

ALTER TABLE "Products" ADD "CreatedByRole" character varying(10) NOT NULL DEFAULT 'LEGACY';

ALTER TABLE "Products" ADD "ImageUrls" text[] NOT NULL DEFAULT (ARRAY[]::text[]);

ALTER TABLE "Products" ADD "RejectionReason" character varying(500);

ALTER TABLE "Products" ADD "ReviewedAt" timestamp with time zone;

ALTER TABLE "Products" ADD "ReviewedById" integer;

ALTER TABLE "Products" ADD "Status" character varying(16) NOT NULL DEFAULT 'PENDING';

ALTER TABLE "Products" ADD "Unit" character varying(10) NOT NULL DEFAULT 'piece';

ALTER TABLE "Products" ADD "UpdatedAt" timestamp with time zone;

ALTER TABLE "Products" ADD "Version" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Products" ADD "WeightKg" numeric(12,3);

CREATE INDEX "IX_Products_CreatedById" ON "Products" ("CreatedById");

CREATE INDEX "IX_Products_ReviewedById" ON "Products" ("ReviewedById");

CREATE INDEX "IX_Products_Status_CreatedAt" ON "Products" ("Status", "CreatedAt");

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Users_ReviewedById" FOREIGN KEY ("ReviewedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908193454_AddProductManagement', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" ADD "ImageUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908203604_AddCategoryImage', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ADD "Address" text;

ALTER TABLE "Users" ADD "City" text;

ALTER TABLE "Users" ADD "Province" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260909075537_AddUserAddress', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ADD "ProfileImageUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260909082245_AddUserProfileImage', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Carts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CartItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_CartItems_CartId_ProductId" ON "CartItems" ("CartId", "ProductId");

CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");

CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260910173839_AddCustomerCart', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "CustomerOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "RequestId" uuid NOT NULL,
    "RequestHash" text NOT NULL,
    "Status" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Address" text NOT NULL,
    "City" text NOT NULL,
    "Currency" text NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "DeliveryFee" numeric(18,2) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "ReviewReason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CustomerOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerOrders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CustomerOrderLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Name" text NOT NULL,
    "Unit" text NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "SourceCartItemId" integer,
    CONSTRAINT "PK_CustomerOrderLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerOrderLines_CustomerOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "CustomerOrders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CustomerPayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Method" text NOT NULL,
    "Status" text NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "GatewayOrderId" text NOT NULL,
    "ProviderPaymentId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PaidAt" timestamp with time zone,
    CONSTRAINT "PK_CustomerPayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerPayments_CustomerOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "CustomerOrders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CustomerOrderLines_OrderId" ON "CustomerOrderLines" ("OrderId");

CREATE UNIQUE INDEX "IX_CustomerOrders_UserId_RequestId" ON "CustomerOrders" ("UserId", "RequestId");

CREATE UNIQUE INDEX "IX_CustomerPayments_GatewayOrderId" ON "CustomerPayments" ("GatewayOrderId");

CREATE UNIQUE INDEX "IX_CustomerPayments_OrderId" ON "CustomerPayments" ("OrderId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260910212627_AddCustomerPurchaseFlow', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "CustomerOrderStatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ChangedByUserId" integer NOT NULL,
    "FromStatus" character varying(40) NOT NULL,
    "ToStatus" character varying(40) NOT NULL,
    "Note" character varying(500),
    "PaymentCollected" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CustomerOrderStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerOrderStatusHistories_CustomerOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "CustomerOrders" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CustomerOrderStatusHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_CustomerOrders_Status_CreatedAt" ON "CustomerOrders" ("Status", "CreatedAt");

CREATE INDEX "IX_CustomerOrderStatusHistories_ChangedByUserId" ON "CustomerOrderStatusHistories" ("ChangedByUserId");

CREATE INDEX "IX_CustomerOrderStatusHistories_OrderId_CreatedAt" ON "CustomerOrderStatusHistories" ("OrderId", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260915135053_AddAdminOrderStatusHistory', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ADD "PasswordResetExpiresAt" timestamp with time zone;

ALTER TABLE "Users" ADD "PasswordResetFailedAttempts" integer NOT NULL DEFAULT 0;

ALTER TABLE "Users" ADD "PasswordResetHash" text;

ALTER TABLE "Users" ADD "PasswordResetLastSentAt" timestamp with time zone;

ALTER TABLE "Users" ADD "PasswordResetSendCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "Users" ADD "PasswordResetWindowStart" timestamp with time zone;

ALTER TABLE "Users" ADD "SessionStamp" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260915203908_AddPasswordResetAndSessionStamp', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "IsFood" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Products" ADD "NutritionBasis" text;

ALTER TABLE "Products" ADD "NutritionFacts" text;

ALTER TABLE "Products" ADD "NutritionSourceName" text;

ALTER TABLE "Products" ADD "NutritionSourceUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260916110233_AddProductNutrition', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "SmartBasketWorkflows" (
    "Id" uuid NOT NULL,
    "CustomerId" integer NOT NULL,
    "RequestId" uuid NOT NULL,
    "RequestHash" character varying(64) NOT NULL,
    "Objective" character varying(1000) NOT NULL,
    "Budget" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "ConstraintsJson" jsonb NOT NULL,
    "Status" character varying(30) NOT NULL,
    "PlanJson" jsonb NOT NULL,
    "ValidationJson" jsonb NOT NULL,
    "ProposedTotal" numeric(18,2) NOT NULL,
    "ProposalRevision" integer NOT NULL,
    "FailureReason" character varying(2000),
    "AttemptCount" integer NOT NULL,
    "LeaseOwner" character varying(100),
    "LeaseExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "Version" uuid NOT NULL,
    CONSTRAINT "PK_SmartBasketWorkflows" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SmartBasketWorkflow_Budget" CHECK ("Budget" > 0),
    CONSTRAINT "CK_SmartBasketWorkflow_Status" CHECK ("Status" IN ('Pending', 'Planning', 'Validating', 'AwaitingApproval', 'Approved', 'Rejected', 'Failed')),
    CONSTRAINT "CK_SmartBasketWorkflow_Total" CHECK ("ProposedTotal" >= 0 AND "ProposedTotal" <= "Budget"),
    CONSTRAINT "FK_SmartBasketWorkflows_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SmartBasketApprovals" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkflowId" uuid NOT NULL,
    "ProposalRevision" integer NOT NULL,
    "AdminId" integer NOT NULL,
    "Decision" character varying(30) NOT NULL,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SmartBasketApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SmartBasketApproval_Decision" CHECK ("Decision" IN ('Approved', 'Rejected', 'RevisionRequested')),
    CONSTRAINT "CK_SmartBasketApproval_Revision" CHECK ("ProposalRevision" > 0),
    CONSTRAINT "FK_SmartBasketApprovals_SmartBasketWorkflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "SmartBasketWorkflows" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SmartBasketApprovals_Users_AdminId" FOREIGN KEY ("AdminId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SmartBasketItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkflowId" uuid NOT NULL,
    "ProposalRevision" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductName" character varying(150) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_SmartBasketItems" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SmartBasketItem_Price" CHECK ("UnitPrice" > 0),
    CONSTRAINT "CK_SmartBasketItem_Quantity" CHECK ("Quantity" > 0),
    CONSTRAINT "CK_SmartBasketItem_Revision" CHECK ("ProposalRevision" > 0),
    CONSTRAINT "FK_SmartBasketItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SmartBasketItems_SmartBasketWorkflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "SmartBasketWorkflows" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SmartBasketSteps" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkflowId" uuid NOT NULL,
    "Attempt" integer NOT NULL,
    "Sequence" integer NOT NULL,
    "AgentName" character varying(80) NOT NULL,
    "ToolName" character varying(100),
    "Status" character varying(30) NOT NULL,
    "InputJson" jsonb NOT NULL,
    "OutputJson" jsonb NOT NULL,
    "ErrorMessage" character varying(2000),
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone,
    CONSTRAINT "PK_SmartBasketSteps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SmartBasketSteps_SmartBasketWorkflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "SmartBasketWorkflows" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SmartBasketApprovals_AdminId" ON "SmartBasketApprovals" ("AdminId");

CREATE UNIQUE INDEX "IX_SmartBasketApprovals_WorkflowId_ProposalRevision" ON "SmartBasketApprovals" ("WorkflowId", "ProposalRevision");

CREATE INDEX "IX_SmartBasketItems_ProductId" ON "SmartBasketItems" ("ProductId");

CREATE UNIQUE INDEX "IX_SmartBasketItems_WorkflowId_ProposalRevision_ProductId" ON "SmartBasketItems" ("WorkflowId", "ProposalRevision", "ProductId");

CREATE UNIQUE INDEX "IX_SmartBasketSteps_WorkflowId_Attempt_Sequence" ON "SmartBasketSteps" ("WorkflowId", "Attempt", "Sequence");

CREATE UNIQUE INDEX "IX_SmartBasketWorkflows_CustomerId_RequestId" ON "SmartBasketWorkflows" ("CustomerId", "RequestId");

CREATE INDEX "IX_SmartBasketWorkflows_Status_CreatedAt" ON "SmartBasketWorkflows" ("Status", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260916152356_AddSmartBasketWorkflow', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SmartBasketWorkflows" DROP CONSTRAINT "CK_SmartBasketWorkflow_Status";

ALTER TABLE "SmartBasketWorkflows" ADD CONSTRAINT "CK_SmartBasketWorkflow_Status" CHECK ("Status" IN ('Pending', 'Planning', 'Validating', 'AwaitingCustomerReview', 'AwaitingApproval', 'Approved', 'Rejected', 'Failed'));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260919194837_AddSmartBasketCustomerReview', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SmartBasketWorkflows" DROP CONSTRAINT "CK_SmartBasketWorkflow_Status";

ALTER TABLE "CustomerOrders" ADD "SmartBasketRevision" integer;

ALTER TABLE "CustomerOrders" ADD "SmartBasketWorkflowId" uuid;

ALTER TABLE "SmartBasketWorkflows" ADD CONSTRAINT "CK_SmartBasketWorkflow_Status" CHECK ("Status" IN ('Pending', 'Planning', 'Validating', 'AwaitingCustomerReview', 'AwaitingApproval', 'Approved', 'Rejected', 'Failed', 'Ordered'));

CREATE UNIQUE INDEX "IX_CustomerOrders_SmartBasketWorkflowId" ON "CustomerOrders" ("SmartBasketWorkflowId");

ALTER TABLE "CustomerOrders" ADD CONSTRAINT "CK_CustomerOrder_SmartBasketLink" CHECK (("SmartBasketWorkflowId" IS NULL AND "SmartBasketRevision" IS NULL) OR ("SmartBasketWorkflowId" IS NOT NULL AND "SmartBasketRevision" IS NOT NULL AND "SmartBasketRevision" > 0));

ALTER TABLE "CustomerOrders" ADD CONSTRAINT "FK_CustomerOrders_SmartBasketWorkflows_SmartBasketWorkflowId" FOREIGN KEY ("SmartBasketWorkflowId") REFERENCES "SmartBasketWorkflows" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260920153548_LinkSmartBasketToCustomerOrder', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SmartBasketWorkflows" DROP CONSTRAINT "CK_SmartBasketWorkflow_Status";

ALTER TABLE "SmartBasketWorkflows" ADD CONSTRAINT "CK_SmartBasketWorkflow_Status" CHECK ("Status" IN ('Pending', 'Planning', 'Validating', 'AwaitingCustomerReview', 'AwaitingApproval', 'Approved', 'Rejected', 'Failed', 'Ordered', 'Deleted'));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260921133004_AddSmartBasketDeletedStatus', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260921133103_AddDeletedSmartBasketStatus', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Farms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FarmerId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Location" character varying(200),
    "TotalArea" numeric(10,2) NOT NULL,
    "AreaUnit" character varying(20) NOT NULL DEFAULT 'Acres',
    "SoilType" character varying(50),
    "IrrigationType" character varying(50),
    "MainCrops" character varying(250),
    "Description" character varying(1000),
    "ImageUrls" text[] NOT NULL DEFAULT (ARRAY[]::text[]),
    "Status" character varying(20) NOT NULL DEFAULT 'ACTIVE',
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Farms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Farms_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Farms_FarmerId" ON "Farms" ("FarmerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260924105148_AddFarmsManagement', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Packages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Category" character varying(20) NOT NULL,
    "BaseRate" numeric(12,2) NOT NULL,
    "MinimumCharge" numeric(12,2),
    "CropType" character varying(100),
    "QuantityPerAcreKg" numeric(12,2),
    "MaxLoadKg" numeric(12,2),
    "RatePerExtraKg" numeric(12,2),
    "IsActive" boolean NOT NULL,
    "CreatedById" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Version" uuid NOT NULL,
    CONSTRAINT "PK_Packages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Packages_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PackageBookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PackageId" integer NOT NULL,
    "FarmerId" integer NOT NULL,
    "LandSizeAcres" numeric(12,2),
    "DistanceKm" numeric(12,2),
    "LoadWeightKg" numeric(12,2),
    "CalculatedQuantity" numeric(12,2) NOT NULL,
    "TotalPrice" numeric(12,2) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'PENDING',
    "Notes" character varying(500),
    "AdminNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Version" uuid NOT NULL,
    CONSTRAINT "PK_PackageBookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PackageBookings_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "Packages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PackageBookings_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PackageBookings_FarmerId" ON "PackageBookings" ("FarmerId");

CREATE INDEX "IX_PackageBookings_PackageId" ON "PackageBookings" ("PackageId");

CREATE INDEX "IX_PackageBookings_Status" ON "PackageBookings" ("Status");

CREATE INDEX "IX_Packages_Category" ON "Packages" ("Category");

CREATE INDEX "IX_Packages_CreatedById" ON "Packages" ("CreatedById");

CREATE INDEX "IX_Packages_IsActive" ON "Packages" ("IsActive");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260925125611_AddPackagesAndBookings', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "SmartBasketWorkflows" DROP CONSTRAINT "CK_SmartBasketWorkflow_Budget";

ALTER TABLE "SmartBasketWorkflows" DROP CONSTRAINT "CK_SmartBasketWorkflow_Total";

ALTER TABLE "SmartBasketWorkflows" ALTER COLUMN "Budget" DROP NOT NULL;

ALTER TABLE "SmartBasketWorkflows" ADD CONSTRAINT "CK_SmartBasketWorkflow_Budget" CHECK ("Budget" IS NULL OR "Budget" > 0);

ALTER TABLE "SmartBasketWorkflows" ADD CONSTRAINT "CK_SmartBasketWorkflow_Total" CHECK ("ProposedTotal" >= 0 AND ("Budget" IS NULL OR "ProposedTotal" <= "Budget"));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260928114136_OptionalSmartBasketBudget', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Packages" ADD "ImageUrlsJson" text NOT NULL DEFAULT '[]';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260929191404_AddPackageImages', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "PackageBookings" ADD "FarmId" integer;

ALTER TABLE "PackageBookings" ADD "FarmLocation" text;

ALTER TABLE "PackageBookings" ADD "FarmName" text;

ALTER TABLE "PackageBookings" ADD "ServiceDate" date;

CREATE INDEX "IX_PackageBookings_FarmId" ON "PackageBookings" ("FarmId");

CREATE INDEX "IX_PackageBookings_ServiceDate" ON "PackageBookings" ("ServiceDate");

ALTER TABLE "PackageBookings" ADD CONSTRAINT "FK_PackageBookings_Farms_FarmId" FOREIGN KEY ("FarmId") REFERENCES "Farms" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260929222453_AddNotesToPackageBooking', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260929222531_AddBookingFarmDateAndLifecycle', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "IsActive" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930140416_AddProductAvailability', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "PackageBookings" ADD "AdvanceAmount" numeric(12,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "PackageBookings" ADD "AmountPaid" numeric(12,2) NOT NULL DEFAULT 0.0;

ALTER TABLE "PackageBookings" ADD "PaymentStatus" character varying(20) NOT NULL DEFAULT 'NOT_REQUIRED';

ALTER TABLE "PackageBookings" ADD "RequiresAdvancePayment" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "PackagePaymentProofs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookingId" integer NOT NULL,
    "Stage" character varying(10) NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "TransferReference" character varying(100) NOT NULL,
    "ReceiptFileName" character varying(100) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "AdminNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedById" integer,
    "Version" uuid NOT NULL,
    CONSTRAINT "PK_PackagePaymentProofs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PackagePaymentProofs_PackageBookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "PackageBookings" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PackagePaymentProofs_Users_ReviewedById" FOREIGN KEY ("ReviewedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_PackagePaymentProofs_BookingId_Stage" ON "PackagePaymentProofs" ("BookingId", "Stage") WHERE "Status" IN ('SUBMITTED', 'APPROVED');

CREATE INDEX "IX_PackagePaymentProofs_ReviewedById" ON "PackagePaymentProofs" ("ReviewedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930151311_AddPackagePaymentProofs', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930151759_AddPackageBankTransferPayments', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "OrderPaymentProofs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "TransferReference" character varying(100) NOT NULL,
    "Receipt" bytea NOT NULL,
    "ContentType" character varying(30) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "AdminNote" character varying(500),
    "ReviewedById" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "Version" uuid NOT NULL,
    CONSTRAINT "PK_OrderPaymentProofs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderPaymentProofs_CustomerOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "CustomerOrders" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderPaymentProofs_Users_ReviewedById" FOREIGN KEY ("ReviewedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_OrderPaymentProofs_OrderId" ON "OrderPaymentProofs" ("OrderId") WHERE "Status" IN ('SUBMITTED', 'APPROVED');

CREATE INDEX "IX_OrderPaymentProofs_ReviewedById" ON "OrderPaymentProofs" ("ReviewedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930193323_AddOrderPaymentProofs', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "FarmerNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FarmerId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_FarmerNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FarmerNotifications_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_FarmerNotifications_FarmerId_CreatedAt" ON "FarmerNotifications" ("FarmerId", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261001112425_AddFarmerNotifications', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "FarmAiAnalyses" (
    "Id" uuid NOT NULL,
    "RequestId" uuid NOT NULL,
    "FarmerId" integer NOT NULL,
    "FarmId" integer,
    "SourceFarmId" integer NOT NULL,
    "FarmName" character varying(200) NOT NULL,
    "Objective" character varying(500) NOT NULL,
    "Status" character varying(32) NOT NULL,
    "RequestJson" jsonb NOT NULL,
    "InputJson" jsonb NOT NULL,
    "ResultJson" jsonb,
    "ErrorCode" character varying(80),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_FarmAiAnalyses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FarmAiAnalyses_Farms_FarmId" FOREIGN KEY ("FarmId") REFERENCES "Farms" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_FarmAiAnalyses_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_FarmAiAnalyses_FarmerId_CreatedAt" ON "FarmAiAnalyses" ("FarmerId", "CreatedAt");

CREATE INDEX "IX_FarmAiAnalyses_FarmId" ON "FarmAiAnalyses" ("FarmId");

CREATE UNIQUE INDEX "UX_FarmAiAnalysis_Request" ON "FarmAiAnalyses" ("FarmerId", "RequestId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261001161547_AddFarmAiAnalyses', '8.0.11');

COMMIT;

